__title__ = 'db_cache'
__description__ = 'DB Cache'
__url__ = 'https://github.com/dskrypa/db_cache'
__version__ = '2022.10.14-2'
__author__ = 'Doug Skrypa'
__author_email__ = 'dskrypa@gmail.com'
__copyright__ = 'Copyright 2022 Doug Skrypa'
